---
# Server options
socket: tmp/sockets/thin.sock
chdir: /appli/seb-app/current

# SSL options
#ssl: true

# Adapter options
environment: production

# Daemon options
daemonize: true
log: log/thin.log
pid: tmp/pids/thin.pid
user: app
group: app
tag: smoothiefunds@production

# Cluster options
#servers: 1
onebyone: true
wait: 30

# Tuning options
timeout: 30
max_conns: 1024
max_persistent_conns: 512
threaded: true
no-epoll: true

# Common options
#require: []
