# https://rubocop.readthedocs.io/en/latest/

# I always use double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Specific to my eccentric comments
Layout/ExtraSpacing:
  Exclude:
    - Gemfile

# Well, it's seem it's a rails project
Rails:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: rails
AllCops:
  Exclude:
    - db/schema.rb

# too much work for now
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
