# https://rubocop.readthedocs.io/en/stable/
require:
  - rubocop-performance
  - rubocop-rails

# Preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Specific to my eccentric comments
Layout/ExtraSpacing:
  Exclude:
    - Gemfile

# Well, it's seem it's a rails project
Rails:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*

# too much work for now
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
