# https://rubocop.readthedocs.io/en/stable/

# Preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Specific to my eccentric comments
Layout/ExtraSpacing:
  Exclude:
    - Gemfile

# Well, it's seem it's a rails project
Rails:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: rails
AllCops:
  Exclude:
    - db/schema.rb
    - bin/setup     # https://github.com/rubocop-hq/rubocop-rails/issues/13
    - bin/update    # https://github.com/rubocop-hq/rubocop-rails/issues/13

# too much work for now
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
