# https://rubocop.readthedocs.io/en/stable/
require:
  - rubocop-performance
  - rubocop-rails

# rubocop requirement
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

# Preferences
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Specific to my eccentric comments
Layout/ExtraSpacing:
  Exclude:
    - Gemfile

# Well, it's seem it's a rails project
Rails:
  Enabled: true
AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*

# too much work for now
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
