# https://rubocop.readthedocs.io/en/stable/
require:
  - rubocop-md
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

# pending Cops
AllCops:
  NewCops: enable

# Preferences
Layout/HashAlignment:
  EnforcedColonStyle: table

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Minitest/AssertPredicate:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 15

# intentionally excluded
Rails/ActionControllerFlashBeforeRender:
  Exclude:
    - app/controllers/transactions_controller.rb

# too much work for now
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
