# https://rubocop.readthedocs.io/en/latest/

# I always use double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Well, it's seem it's a rails project
Rails:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: rails

# Specific to my eccentric comments
Layout/ExtraSpacing:
  Exclude:
    - Gemfile
