# PostgreSQL + SQLite in production pending data migration
#
default_sqlite: &default_sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default_sqlite
  database: storage/development.sqlite3

test:
  <<: *default_sqlite
  database: storage/test.sqlite3

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    host: <%= ENV["DATABASE_HOST"] || "172.18.0.1" %>
    database: <%= ENV["DATABASE_NAME"] %>
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
  cache:
    <<: *default_sqlite
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default_sqlite
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default_sqlite
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
