# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d16f541ca5baaea4f936a03d36338b81e2d43a03405c01bf047a7bdb4602fe78a604f8b5e08c049edff886140ed979e650c25d6f13ad77295d48b43f8366065

test:
  secret_key_base: 407717f73ef549cbbf0511fcca13ad6e41a8192d16690bc4ef66f6de3197a4104d70f9cdcd17f2618d4eef927215817562cc2b75b8a1ee6c100778ba6d3e7bf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
